### ISSUE TITLE
这个qemu的virtio-blk-device能否使用

### ISSUE THREAD

**Issue by ljy2017** [Godones/rCoreloongArch#3]
请问，这个qemu的virtio-blk-device无法使用吗，但我看它的支持列表里有virtio-blk-device呢

**Comment by Godones** [comment]
@ljy2017 loongarch64中对virtio设备好像不支持，至少在qemu6.2.5上，最新的版本我没有查看

**Comment by ljy2017** [comment]
十分感谢回答，能在问一下，您是怎么确定的吗，想了解一下

**Comment by ljy2017** [comment]
十分感谢回答，能在问一下，您是怎么确定的吗，想了解一下

**Comment by ljy2017** [comment]
有方法的话，我去确认一下高版本的支不支持

**Comment by Godones** [comment]
可以试试qemu-system-riscv64 -device help 类似的命令
